Add the global.imageRegistry option
codecentric/helm-charts pull request #328
Opened 2020-10-19 11:33 UTC by yardenshoham

This change allows one to specify the image registry which will be used for each image individually, as well as a global image registry to override all image registries.

I used Bitnami's common chart to keep things standard and generic.

This change is extremely beneficial to those who use an airgapped environment with a private image registry.

2020-10-21 07:15 UTC, yardenshoham commented
@thomasdarimont @unguiculus please review and merge.

2020-10-23 09:41 UTC, unguiculus requested changes
I'm open to adding a separate registry configuration option, but I certainly won't accept including the common chart dependency. Also, this should be done in a backwards-compatible way so we don't need to bump the major version.

2020-10-23 11:36 UTC, yardenshoham commented
@unguiculus 
Currently the `image.repository` includes the registry. There is no way to introduce `image.registry` without changing the meaning of `image.repository`. So there is no way to make this change be backwards-compatible.

2020-11-23 08:42 UTC, yardenshoham commented
@unguiculus What do you think?

2020-12-05 14:18 UTC, unguiculus commented
Please remove the common chart dependency and I'll have another look.

2021-02-15 12:21 UTC, closed without merging