Fix ingress
codecentric/helm-charts pull request #352
Opened 2020-11-23 14:45 UTC by RytisLT

Currently, the helm chart fails when ingress is enabled. This pull request adapts ingress.yaml to ingress v1 syntax.

2020-11-24 20:42 UTC, jkroepke commented
Hi,

i'm running Kubernetes 1.19, looks like pathType is required, too:

```yaml
# Source: keycloak/templates/patched.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 11.0.2
    helm.sh/chart: keycloak-9.6.1
  name: keycloak
spec:
  rules:
  - host: example.keycloak.org
    http:
      paths:
      - backend:
          service:
            name: keycloak-http
            port:
              name: http
        path: /
  tls:
  - hosts:
    - example.keycloak.org
    secretName: keycloak-ingress-tls
```

Results into this:
```
  Error: release keycloak failed, and has been uninstalled due to atomic being set: Ingress.extensions "keycloak" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified
```

2020-11-24 20:44 UTC, jkroepke commented on charts/keycloak/templates/ingress.yaml
>            - path: {{ . }}
```suggestion
          - path: {{ . }}
            pathType: Prefix
```

2020-11-25 06:28 UTC, unguiculus requested changes
This is related to this change: #334

The fix needs to consider what API version is used.

2020-11-25 07:18 UTC, RytisLT commented
@unguiculus added ingress version check. I couldn't figure out how to use `keycloak.ingressAPIVersion` inside `if` statement so I've used `.Capabilities` instead.

2020-11-30 10:13 UTC, RytisLT commented
@unguiculus Can you please take another look at the PR I've added the version check?

2020-12-04 11:03 UTC, Flowkap commented
The new versioh will break evetyrhing before K8s 1.19.x so should be v1beta1 still. Related to https://github.com/codecentric/helm-charts/issues/349 https://github.com/codecentric/helm-charts/issues/347

2020-12-04 14:45 UTC, unguiculus approved these changes

2020-12-04 14:46 UTC, merged