Fix Ingress API check in ingress.yaml
codecentric/helm-charts pull request #360
Opened 2020-12-20 13:04 UTC by mteodori

The fix introduced in #357 uses a lowercase check for the Ingress API `networking.k8s.io/v1/ingress` rather than `networking.k8s.io/v1/Ingress` which fails with a cluster version v1.19.3 like the one in the latest Docker Desktop.

This PR fixes that and completes support of the new API with a check for ingress.servicePort as the new yaml is different wether the value is string or int as allowed by the values.schema.json

2021-01-22 08:07 UTC, unguiculus requested changes

2021-01-22 08:07 UTC, unguiculus commented on charts/keycloak/templates/ingress.yaml
> +                  {{ ternary "name" "number" (kindIs "string" $ingress.servicePort) }}: {{ $ingress.servicePort }}
I don't see why we want to change this. It's supposed to be a string. The named port should be referenced.

2021-01-28 16:20 UTC, unguiculus requested changes
You will have to fix DCO.

2021-01-28 18:09 UTC, mteodori commented
> You will have to fix DCO.

done, couldn't find a way to do it from the GitHub UI though, also the conflict resolution...

2021-01-29 09:04 UTC, unguiculus approved these changes

2021-01-29 09:06 UTC, merged

2021-01-29 09:35 UTC, mteodori commented
thanks @unguiculus !

2021-10-20 22:05 UTC, juliohm1978 commented
Has this been tested? It's not working for me. The chart never renders `apiVersion: networking.k8s.io/v1` because the Capability list does not contain `networking.k8s.io/v1/Ingress`. The list actually has `networking.k8s.io/v1`.