fix: apply secret type configed in values file
codecentric/helm-charts pull request #398
Opened 2021-02-19 13:51 UTC by WaylandWong

specify secrets's type.
https://github.com/codecentric/helm-charts/issues/324

2021-02-19 14:02 UTC, unguiculus requested changes
Thanks. Please fix DCO and bump the chart version.

Also, please update the comment in the values file:
https://github.com/codecentric/helm-charts/blob/master/charts/keycloak/values.yaml#L209-L214

2021-02-19 14:02 UTC, unguiculus commented on charts/keycloak/templates/secrets.yaml
> +{{- end }}
I'd suggest you simply this:
```suggestion
type: {{ default $values.type "Opaque" }}
```

2021-02-20 12:27 UTC, WaylandWong commented on charts/keycloak/templates/secrets.yaml
> +{{- end }}
Good idea. And I think it would be 
```
type: {{ default "Opaque" $values.type}}
```

2021-02-20 12:52 UTC, WaylandWong commented
I change the version to `9.9.5`, so please merge #40 first.

2021-02-21 17:29 UTC, unguiculus commented on charts/keycloak/templates/secrets.yaml
> +{{- end }}
You're right, of course 😉

2021-02-21 17:43 UTC, unguiculus approved these changes

2021-02-21 17:44 UTC, merged