[keycloak] add ingress.console (#335)
codecentric/helm-charts pull request #406
Opened 2021-03-08 10:34 UTC by olivierboudet

Add ingress.console part to create specific ingress for admin console access. This allow to have specific annotations for /auth/admin access such as `nginx.ingress.kubernetes.io/whitelist-source-range`

Signed-off-by: Olivier Boudet <o.boudet@gmail.com>

2021-03-09 16:27 UTC, olivierboudet commented on charts/keycloak/README.md
> +| `ingress.console.rules[0].host` | Host for the Ingress rule for the console | `keycloak.example.com` |
Ok, I changed it. I changed also the readme for ingress.tls[0].host as the default value is the same and not reflected correctly.

2021-03-09 21:06 UTC, unguiculus requested changes

2021-03-09 21:06 UTC, unguiculus commented on charts/keycloak/Chart.yaml
> +version: 10.0.1
Please bump the minor version for a new feature

2021-03-12 10:58 UTC, mircohaug approved these changes

2021-03-12 11:03 UTC, mircohaug approved these changes
LGTM

2021-03-12 11:12 UTC, thomasdarimont approved these changes
LGTM

2021-03-12 12:06 UTC, merged