[keycloak] Adding NodeSelector to Test Pod definition
codecentric/helm-charts pull request #414
Opened 2021-03-30 17:54 UTC by behrad84

Hello Codecentric,

I think it is good idea to modify Test Pod definition to include NodeSelector if it is defined in values file for deploying a test pod in the right node.

2021-04-09 14:15 UTC, mircohaug requested changes

2021-04-09 14:15 UTC, mircohaug commented on charts/keycloak/Chart.yaml
> +version: 10.1.1
```suggestion
version: 10.2.1
```
The version need to increase with each release. I just merged another PR so there is no fault on your side.

2021-04-30 09:55 UTC, mircohaug commented
Sorry i tried to rebase your branch and messed it up :-( i think you have to create a new PR. Sorry again.

2021-05-10 14:54 UTC, mamirsoltani commented
@mircohaug this PR can be closed.

2021-05-21 08:20 UTC, closed without merging