fix: auth volume overwritten when outgoingSMTP.enabled
codecentric/helm-charts pull request #538
Opened 2022-02-02 12:59 UTC by dnplkndll

now:
when outgoingSMTP.enabled and auth.enabled the SMTP volume write to the root volumes key

fix:
make the volume key either or and add to the array of volume to support either or both

2022-02-02 15:47 UTC, dnplkndll commented
@thomasdarimont tested this and resolves the issue with both on at the same time, did not test every permutation. but hoping to get this merged so I do not have to publish from a fork.

2022-02-02 23:07 UTC, dnplkndll commented
@max3903 are you guys still using this email trap?

2022-02-02 23:15 UTC, max3903 commented
@dnplkndll Yes

2022-02-02 23:15 UTC, max3903 commented
Ping @JevinD

2022-02-04 23:42 UTC, dnplkndll commented
@patrys I saw you reference the image. do you use this chart or just the image? https://github.com/saleor/saleor-platform/blob/main/docker-compose.yml#L112

2022-02-11 14:03 UTC, mircohaug requested changes
Thanks for contributing. Please fix this tiny thing and I will merge the PR.

2022-02-11 14:03 UTC, mircohaug commented on charts/mailhog/templates/deployment.yaml
> +      {{ end }}
Please move this `{{ end }}` to the end of the volumes block. This works as well but the proposed change is more clear. I would have added it to the PR myself bu you did not allow PR edits...

2022-03-03 17:23 UTC, dnplkndll commented
> Thanks for contributing. Please fix this tiny thing and I will merge the PR.

anything else you need on this?

2022-03-25 13:40 UTC, mircohaug approved these changes

2022-03-25 13:41 UTC, merged