add namespace attribute in keycloakx objects
codecentric/helm-charts pull request #584
Opened 2022-04-26 12:00 UTC by bovy89

Signed-off-by: bovy89 <bovy89@gmail.com>

2022-04-27 07:50 UTC, PSanetra commented
Hi @bovy89, can you tell us more about the use case for this change? I think at least the changes related to setting the namespace fields to `.Release.Namespace` seem to be unnecessary.

2022-04-27 08:03 UTC, bovy89 commented
Some tools are using helm template (`helm template -n <namespace>`) to generate a static manifest. That change is also helpful to include namespace info in order to exclude an entire namespace from automated testing (we are using trivy rego rules) without using anything else (i.e. kustomize).

Some honorable mentions of charts that are doing that:
- https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/prometheus
- https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

2022-05-13 09:50 UTC, mircohaug requested changes
Thanks for the contribution, please also add `{{ .Release.Namespace }}` as default when for the resources where namespace overwrites are possible. Namely the `PrometheusRule` you added the overwrite for but also the `ServiceMonitor` resource where this overwrite already exists

2022-05-13 09:50 UTC, mircohaug commented on charts/keycloakx/templates/prometheusrule.yaml
> +  namespace: {{ . }}
This needs to default explicitly to `{{ .Release.Namespace }}` as well

2022-07-19 09:42 UTC, bovy89 commented
Any update?

2022-07-28 13:00 UTC, grieshaber commented
hey @bovy89 thanks for this PR. We had some changes in the maintainer team recently and lost a little bit of track.
I'll check your chages real quick and merge the PR if nothing comes up.

2022-07-28 13:04 UTC, grieshaber approved these changes

2022-07-28 13:04 UTC, merged