[mailhog] Add ability to definit targetPort of name based service or not
codecentric/helm-charts pull request #632
Opened 2022-08-02 21:36 UTC by jullianow

Named target ports are not supported by GCE health checks, so when deploying in GKE and exposing it via GCE ingress, the health checks fail and the load balancer returns a 502.

Signed-off-by: Julliano Goncalves <jullianow@gmail.com>

2022-09-08 02:43 UTC, jullianow commented
Ping

2022-09-26 09:37 UTC, grieshaber requested changes

2022-09-26 09:37 UTC, grieshaber commented on charts/mailhog/values.yaml
> +    port: *containerSmtpPort
I see, what you try to achieve here - but imho this is not considered best practice to use the yaml anchors with helm.

i'd say, tackle the behaviour you want to achieve in the templates directly - so skip the definition in the _defaults_ here and access containerPort in the template or livenessProbe Port when defined.

2022-12-03 12:12 UTC, jullianow commented
Ping

2023-01-20 14:09 UTC, jullianow commented
Ping

2023-01-31 20:24 UTC, jullianow commented
@grieshaber Can we walk with this PR?

2023-02-01 07:04 UTC, merged

2023-02-01 11:44 UTC, grieshaber commented
Hey @jullianow, 
the release will be created automatically tomorrow afternoon. (Most likely not following semvar best-practices, as the release mechanism is not correctly used and enforced unfortunately).

2023-02-01 11:55 UTC, jullianow commented
Sorry, but I don't think I understand.  The graph version will not be generated following the semver-based version evocation pattern, but a version will be generated following another pattern?

2023-02-01 11:56 UTC, jullianow commented
@grieshaber I have a curiosity.  Do you know or maintain the Mailhog application repository?  Do you have any news why the PRs there are “half stopped”?